---
port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title: "Kotlin Stand @ FOSDEM"
keywords: "kotlin, fosdem, open source, developers, conference, meetup, call for paper, oss"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/Kotlin-FOSDEM/kotlin-fosdem.github.io"
favicon: "img/favicon.ico"
touch_icon: "img/apple-touch-icon.png"
google_analytics_key: ""

### template colors, used site-wide via css ###
colors:
  black: "#18171B"
  white: "#f8f8f8"
  fosdempurplelight: "#C484A3"
  fosdempurpledark: "#AB1C93"
  fosdemgraylight: "#D4D4D4"
  fosdemgraymid: "#A4A4A4"
  fosdemgraydark: "#818081"
  fosdemblack: "#18171B"
  blue: "#49a7e9"
  green: "#9bcf2f"
  purple: "#c869bf"
  orange: "#fab125"
  turquoise: "#0fbfcf"

kramdown:
  auto_ids: false
